### ISSUE TITLE
Simulations that are restarted do not follow mcadence output

### ISSUE THREAD

**Issue by jdiazpena** [gemini3d/gemini3d#108]
When creating a simulation with flagoutput=2 for average parameters is used with the inclusion mcadence to get full outputs for some times and the simulation is stopped, restarting it causes it to ignore mcadence. 

When restarting the simulation, gemini3d ignores mcadence, looks for the latest full output, erases it, and starts the simulation again, only using average outputs for the rest of the simulation. It makes it impossible to stop and restart again since it will look for the first full output (which is now earlier) and do the same process.

**Comment by mattzett** [comment]
I also just ran across this bug.  ```tmilestone``` needs to be set at the beginning of a simulation.  For a new simulation it is just set to zero, but for a restart it should be set to whatever the beginning time is (currently it is not).

**Comment by mattzett** [comment]
This has been fixed here:  https://github.com/gemini3d/gemini3d/commit/032d5e5ad7fc6d6a8618b5c6f8bebdfec63011a0
