### ISSUE TITLE
error in Fortran MPI image count check

### ISSUE THREAD

**Issue by scivision** [gemini3d/gemini3d#17]
Currently numerical/grid/grid.f90:grid_check() does some basic sanity checks. However a lot of bad cases can get through, causing a non-obvious error like putting NaNs in plasma variables or MUMPS failing to solve. Normally, the Python front-end will only give "good" number of MPI images. However if a user *manually* specifies the number of MPI images, grid_check() often doesn't catch the problem, and so we get NaN check errors or MUMPS memory errors.

### Examples triggering error

there are many more cases that will fail, this is just one example of each.

#### NaN in v1

```sh
python scripts/run_test.py 2dew_fang mpiexec.exe build/gemini.bin.exe build/test2dew_fang -np 3
```

(now fixed)

#### mumps error

```sh
python scripts/run_test.py 2dew_fang mpiexec.exe build/gemini.bin.exe build/test2dew_fang -np 7
```

**Comment by mattzett** [comment]
We continue to have issues with the mpi image count checking and init.  As of the latest commit specifying a manual grid is the only way to be sure that it will run correctly...

**Comment by scivision** [comment]
This has been fixed by checks so that these configurations promptly error like:

```
ERROR:grid_size_root: Number of MPI images along x3     7 not a factor of lx3all:     40
```
