### ISSUE TITLE
Full simulation tests need to clear out prior data

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#35]
If you run ctest more than once it will fail the second (and subsequent) times on the full simulation tests (e.g. test2dns_fang) because of the restart functionality which will try to start it from the last file that it finds, which is the final simulation time.  I think ctest needs to clear the output data before it runs so every time you run ctest it will start the simulations from the beginning.

**Comment by mattzett** [comment]
I can confirm that manually deleting the test output data before ctest is run again resolves this problem

**Comment by mattzett** [comment]
This requires ctest clearing out the data but also requires gemini to make sure it is not starting from the last time step...

**Comment by mattzett** [comment]
In the new lagrangian branch I have the fortran code error out if you try to restart from the last time step.

**Comment by scivision** [comment]
OK I applied the zero duration check to master branch as well
