### ISSUE TITLE
hdf5 not autobuilding

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#39]
If it's a problem getting Gemini to build (compile), please let us know the output of these commands (stopping at the command that fails)

```sh
cmake -B build
```

```
-- HDF5 include: /usr/local/include
-- HDF5 library: /usr/local/lib/libhdf5_hl_fortran.a;/usr/local/lib/libhdf5_hl.a;/usr/local/lib/libhdf5.a;/usr/local/lib/libhdf5_fortran.a;/usr/local/lib/libhdf5.a;/usr/local/lib/libhdf5_fortran.a;/usr/local/lib/libhdf5.a;/usr/local/lib/libhdf5_fortran.a;/usr/local/lib/libhdf5.a;SZIP::SZIP;ZLIB::ZLIB;Threads::Threads;m
-- Performing Test HDF5_compiles_ok
-- Performing Test HDF5_compiles_ok - Failed
-- Performing Test HDF5_runs_ok
-- Performing Test HDF5_runs_ok - Failed
-- h5fortran: HDF5 not working
CMake Error at cmake/h5fortran.cmake:18 (message):
  HDF5 was requested but is not available.
Call Stack (most recent call first):
  CMakeLists.txt:60 (include)
```

**Comment by scivision** [comment]
Is this on a system that worked before?

**Comment by scivision** [comment]
HDF5 does not currently autobuild but it could be made to do so, as HDF5 is now essential as well as lapack et al. Previously I said well I don't autobuild MPI, but now MPI is not strictly essential for small simulations.

**Comment by scivision** [comment]
Let's catchup in chat first, as it could be that this is a bug, and your library is fine--or vice versa

**Comment by mattzett** [comment]
Paul is having the same error on our HPC; perhaps we misunderstand how to tell it to download and build hdf5?

**Comment by paulinchin** [comment]
There are several HDF5 version on our HPC (hdf5/1.10.0, hdf5/intel-mpi/intel-compiler/1.10.4, hdf5/intel-mpi/intel-compiler/1.8.19, hdf5/openmpi/intel-compiler/1.8.19, hdf5_18/1.8.18). Seems non of them works. Without HDF5 it compiles OK.

Attach error build file.
[CMakeError.log](https://github.com/gemini3d/gemini3d/files/5218411/CMakeError.log)

Thanks!

**Comment by scivision** [comment]
Key lines from that error log include

```
/cm/shared/apps/gcc/8.3.0/bin/gfortran  -I/cm/shared/apps/hdf5/1.10.0/include  -fimplicit-none -std=f2018 -DHDF5_compiles_ok   -c /scratch/inchinp/GEMINIESF/gemini/build/CMakeFiles/CMakeTmp/src.f90 -o CMakeFiles/cmTC_9c388.dir/src.f90.o
/scratch/inchinp/GEMINIESF/gemini/build/CMakeFiles/CMakeTmp/src.f90:2:4:

 use hdf5, only : h5open_f, h5close_f
    1
Fatal Error: Cannot read module file 'hdf5.mod' opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.
```

This is a common HPC issue of ABI mismatch between compiled library and compiler. Currently HDF5 is a manual download and build but I can make it automatic

**Comment by mattzett** [comment]
Is there a flag to tell cmake to do it manually instead of using the system hdf5?

**Comment by scivision** [comment]
If you have PyGemini installed, do

```sh
gemini_prereqs gcc hdf5
```

that works from any directory

**Comment by paulinchin** [comment]
Some problem with installing PyGEMINI on our HPC.
`Obtaining file:///ihome/home2/inchinp/python/pygemini
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 326, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 526, in prepare_editable_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 161, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/ihome/home2/inchinp/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/ihome/home2/inchinp/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/pip-build-env-k_r2zeis/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/tmp/pip-build-env-k_r2zeis/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 32, in <module>
    from setuptools import windows_support
  File "/tmp/pip-build-env-k_r2zeis/overlay/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/ihome/home2/inchinp/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'`

Same error with Python 3.8, 3.7.5, although "Requirement already satisfied: cffi in ./lib/python3.7/site-packages (1.14.2)" (the package that seems to contain ctypes)

**Comment by scivision** [comment]
That error can happen if libffi-devel is missing on the system. 
I did update "gemini3d" repo to autobuild HDF5 without needing Python.
So if you "git pull" in gemini3d and then "rm -r build" and try to build again with 

```sh
cmake -B build
cmake --build build
```

It should either find your existing HDF5 or automatically build HDF5

**Comment by paulinchin** [comment]
Thanks! It is actually install it, but still gives some errors. I attach CMake logs
here is part related to HDF5:
`-- Could NOT find h5fortran (missing: h5fortran_DIR)
-- Performing Test f18flag
-- Performing Test f18flag - Success
-- Performing Test f2018impnone
-- Performing Test f2018impnone - Success
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS HDF5_HL_LIBRARIES Fortran HL) (found version "")
-- installing HDF5 library in /scratch/inchinp/GEMINIESF/gemini/build/_deps/h5fortran_proj-build/hdf5
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
CMake Error at build/_deps/h5fortran_proj-src/cmake/build_hdf5.cmake:67 (add_library):
  add_library cannot create ALIAS target "HDF5::HDF5" because target "hdf5"
  is imported but not globally visible.
Call Stack (most recent call first):
  build/_deps/h5fortran_proj-src/cmake/hdf5.cmake:36 (include)
  build/_deps/h5fortran_proj-src/CMakeLists.txt:34 (include)`
[CMakeError.log](https://github.com/gemini3d/gemini3d/files/5241291/CMakeError.log)
[CMakeOutput.log](https://github.com/gemini3d/gemini3d/files/5241292/CMakeOutput.log)

**Comment by scivision** [comment]
Thanks I just noticed that error myself. I will need to make a new h5fortran release to fix it.

**Comment by scivision** [comment]
To help me diagnose this, would you be willing to work with h5fortran directly? This is just temporary to speedup the fix.  Once this works then I will have Gemini3D use this new h5fortran version

```sh
cd ~

git clone https://github.com/geospace-code/h5fortran

cd h5fortran

cmake -B build
cmake --build build
```

**Comment by paulinchin** [comment]
It seems work, though gave me again some problems while building with HDF5 (I assume that if HDF5_runs_ok OK, then it should work properly):

`-- Could NOT find h5fortran (missing: h5fortran_DIR)
-- Performing Test f18flag
-- Performing Test f18flag - Success
-- Performing Test f2018impnone
-- Performing Test f2018impnone - Success
-- HDF5: Using hdf5 compiler wrapper to determine Fortran configuration
-- Found HDF5: /scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5_fortran.a;/scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5.a;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.12.0") found components:  Fortran HL 
-- Looking for H5_HAVE_FILTER_SZIP
-- Looking for H5_HAVE_FILTER_SZIP - not found
-- Looking for H5_HAVE_FILTER_DEFLATE
-- Looking for H5_HAVE_FILTER_DEFLATE - found
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- HDF5 include: /scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/include
-- HDF5 library: /scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5hl_fortran.a;/scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5_hl.a;/scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5_fortran.a;/scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5.a;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5_fortran.a;/scratch/inchinp/GEMINIESF/h5fortran/build/hdf5/lib/libhdf5.a;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;ZLIB::ZLIB;Threads::Threads;dl;m
-- Performing Test HDF5_compiles_ok
-- Performing Test HDF5_compiles_ok - Success
-- Performing Test HDF5_runs_ok
-- Performing Test HDF5_runs_ok - Success
-- Performing Test f2008block
-- Performing Test f2008block - Success
-- Performing Test f2008submodule
-- Performing Test f2008submodule - Success`

I was able to compile with such build, but failed some tests (not sure how they are important, never ran them before, and they seems not to be connected with HDF5):
`The following tests FAILED:
	  3 - scalapack:BLACSbasic (Timeout)
	  4 - scalapack:unit:real64 (Timeout)
	  7 - unit:MSISsetup (Failed)
	 12 - unit:potential2 (Timeout)
	 22 - unit:mumps_basic (Timeout)`

**Comment by scivision** [comment]
OK. I reworked the HDF5 finding and building. Unfortunately automatically building HDF5 wasn't robust due to how HDF5  is built internally. So I made a CMake script that doesn't rely on Python that downloads, builds and installs HDF5. It's just a one time command:

```cmake
ctest -S scripts/build_hdf5.cmake -VV
```

that defaults to put HDF5 under ~/lib/hdf5-1.12.0

Those tests that  are failing may also cause Gemini to fail because they're fundamental libraries Gemini builds upon

**Comment by scivision** [comment]
What I would do is from the top gemini3d/ directory

```sh
rm -r build/

ctest -S setup.cmake -VV
```

If that still fails with your system HDF5, here's how to do that from top gemini3d/ directory:

```sh
rm -r build/

ctest -S scripts/build_hdf5.cmake -VV

cmake -B build -DHDF5_ROOT=~/lib/hdf5-1.12.0

cmake --build build

cd build

ctest -V
```

**Comment by scivision** [comment]
I did quite some reworking of how HDF5 is used. I take care of this autobuild via h5fortran, which is handled fully automatically when -Dhdf5=on from Gemini3d (default).
I don't think this is an issue anymore. I have CI test cases specifically for this now, to autobuild HDF5.

Although Gemini is not a monorepo (where all source and libraries are in one giant Git repo) it is capable of a monobuild, where all libraries are built in one "build/" directory. 

h5fortran (via gemini3d) also tests that HDF5 is working, and autobuilds if not working.
