### ISSUE TITLE
Non finite results for first time step following priming

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#40]
When running the code there will sometimes be a non-finite result during the first time step causing the simulation to stop.  Most often it will run correctly if you just reissue the same command (i.e. just run mpirun again with same input etc.).  1e9ad70 (before restarting and priming were added) seems to work fine as long as the input code is adjusted for new hdf5 variable names (nsall, etc.)

**Comment by mattzett** [comment]
This is tough to reproduce, on my system it *most often* happens with a 8x1 process split, but still doesn't not always occur...  It seems to be the case that turning of the potential solver fixes the issue so perhaps this is due to some changes in the potential solver made as part of the milestone refactor.

**Comment by mattzett** [comment]
The code seems to work better with splits in x3 that result in lx3<lx2???

**Comment by mattzett** [comment]
Initial drift problem seems to go away if we comment out pot2perpfield in gemini.f90.  Commenting out similar calls in the potential module allows the simulation to persist longer before failing.  Simulation doesn't fail if both pot2perpfield and potentialsrcterms are not called...

**Comment by mattzett** [comment]
Seems to be garbage popping up in ghost cells during haloing...  Not clear if this is a problem with haloing or some other array out-of-bounds type of error that is trashing the haloed arrays...

**Comment by mattzett** [comment]
From what I can tell if you made the process grid only have one dimension in the periodic direction it would not halo the ghost cells properly...

**Comment by mattzett** [comment]
I think we've fixed this, but I'm not sure; at least the simulation hasn't been crashing with this problem lately...

**Comment by scivision** [comment]
I also think this was resolved with reworking to be sure non-allocated variables weren't used.
