### ISSUE TITLE
build system no longer works with -Dhdf5=off

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#42]
```sh
cmake -B build -Dhdf5=off
cmake --build build -j
```

/ihome/home2/zettergm/zettergmdata/Projects/gemini3d/src/io/milestone.f90:47:28:

flagmilestone=h5f%exists('/nsall')
1
Error: 'exists' at (1) is not a member of the 'hdf5_file' structure

**Comment by mattzett** [comment]
Not sure how to deal with this; what happens to the h5 object when -Dhdf5=off is used...

**Comment by scivision** [comment]
This was fixed in b3e98c4e1ba
