### ISSUE TITLE
Ubuntu ARM64 segfaults while trying to download test data

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#65]
test 1
    Start 1: mini2dns_fang:download

1: Test command: /home/parallels/.local/bin/cmake "-Dname=mini2dns_fang" "-Doutdir:PATH=/home/parallels/Projects/gemini3d/build/mini2dns_fang" "-Drefroot:PATH=/home/parallels/Projects/gemini3d/test_data" "-P" "/home/parallels/Projects/gemini3d/cmake/test/download.cmake"
1: Test timeout computed to be: 180
1: -- TLS status: NOTFOUND
1: CMake Warning at /home/parallels/Projects/gemini3d/cmake/CheckTLS.cmake:21 (message):
1:   TLS seems to be broken on your system.  Download will probably fail.
1:   NOTFOUND
1: Call Stack (most recent call first):
1:   /home/parallels/Projects/gemini3d/cmake/CheckTLS.cmake:28 (check_tls)
1:   /home/parallels/Projects/gemini3d/cmake/test/download.cmake:3 (include)
1: 
1: 
1: -- TLS status: NOTFOUND
1: CMake Warning at /home/parallels/Projects/gemini3d/cmake/CheckTLS.cmake:21 (message):
1:   TLS seems to be broken on your system.  Download will probably fail.
1:   NOTFOUND
1: Call Stack (most recent call first):
1:   /home/parallels/Projects/gemini3d/cmake/test/download.cmake:4 (check_tls)
1: 
1: 
1: -- mini2dns_fang: missing hash file, seeing if we need to download and/or extract
1: -- DOWNLOAD: https://www.dropbox.com/s/lk3ib91eimjub9f/mini2dns_fang.zst?dl=1 => /home/parallels/Projects/gemini3d/test_data/mini2dns_fang.zst  sha256: 6f7682d62a6456634a4e07b8c2ebfd8a54cbb2bb4f306ab2e3f5418a6e51ffda
1/1 Test #1: mini2dns_fang:download ...........***Exception: SegFault  0.40 sec

**Comment by scivision** [comment]
This looks like either the system certificates have a problem or CMake has a certificate problem. I would try:

```
curl -O https://gist.github.com/scivision/704fd0c7600266317748e473f7e47062/raw/3bd1a8375e107db9f14660165e107ecd7b27ab42/CheckTLS.cmake

cmake -P CheckTLS.cmake
```

If the curl command fails, that indicates a problem with the system's certificates. If the script says `TLS status: NOTFOUND` then CMake is broken. Did you `apt install cmake` or?

CMake aarch64 (for ARM64) is provided: https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-aarch64.tar.gz extract that to ~/cmake-3.21 or wherever you prefer, and add ~/cmake-3.21/bin or similar to PATH

**Comment by mattzett** [comment]
I installed cmake from source; is there an extra setup that needs to be done for that?  Neither command above fails; however, the latter doesn't print anything out either, is that correct?

**Comment by scivision** [comment]
I updated the comment above -- I forgot the `curl -L` option to allow redirects, and added the expected print output.

**Comment by scivision** [comment]
A possible issue of compiling CMake from source is that if libssl isn't available, CMake won't be able to connect to most of the internet since it's missing TLS for HTTPS.

**Comment by mattzett** [comment]
Here's the output from curl:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   759  100   759    0     0   3300      0 --:--:-- --:--:-- --:--:--  3300
```

**Comment by mattzett** [comment]
Here we go, this is the cmake output for check TLS:
```
parallels@ubuntu-linux-20-04-desktop:~/Projects/gemini3d/build$ cmake -P CheckTLS.cmake
-- CheckTLS: https://www.howsmyssl.com/a/check => check_tls.json
Segmentation fault (core dumped)
```

**Comment by mattzett** [comment]
I'm using cmake v3.21.0

**Comment by mattzett** [comment]
Do I need to manually install libssl (via apt-get?) and then recompile the cmake source?

**Comment by scivision** [comment]
Yes or even easier I would just download the binary executable by from gemini3d/:
```sh
cmake -P scripts/install_cmake.cmake
```

**Comment by mattzett** [comment]
I still get the same problems even when I try to compile cmake or using your install_cmake.cmake script

**Comment by scivision** [comment]
OK let's do a screen share call on this

**Comment by scivision** [comment]
I think this is a computer-specific issue, like a bad SSL library or CMake binary. Closing for now.
