### ISSUE TITLE
latest main branch build fails to find HDF5

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#72]
This is on an Intel Mac:

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HDF5_C_links
-- Performing Test HDF5_C_links - Success
-- Performing Test HDF5_Fortran_links
-- Performing Test HDF5_Fortran_links - Failed
CMake Error at /usr/local/Cellar/cmake/3.21.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find HDF5 (missing: HDF5_links) (found version "1.10.4")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.21.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindHDF5.cmake:638 (find_package_handle_standard_args)
  CMakeLists.txt:28 (find_package)

**Comment by scivision** [comment]
This should be fixed from 82a8e44f882769173bbe61e5d87e4dee97c550ba onward
