### ISSUE TITLE
Manual Path of the compilers to cmake

### ISSUE THREAD

**Issue by himanshu10140** [gemini3d/gemini3d#87]
Cmake is unable to detect correcct paths to mpi in windows 10. But able to detect for DMPI=off. If an example can be provided for passing the path manually to cmake, it would be helpful.

**Comment by mattzett** [comment]
Thanks for reporting this!  I'm assigning this to scivision as he's our windows guru and can likely help.

**Comment by scivision** [comment]
Are you using Intel oneAPI or GCC via MSYS2? If MSYS2, this is how I set MPI up: https://www.scivision.dev/windows-mpi-msys2/

If MSYS2 bin/  (i.e. where gcc.exe etc is) is on Windows PATH, MPI should just work on Windows. You also need to add to Windows PATH environment variable "C:\Program Files\Microsoft MPI\Bin" when you've installed Microsoft MPI. This is where mpiexec.exe is.

**Comment by himanshu10140** [comment]
<img width="1280" alt="MPI_error" src="https://user-images.githubuserc
<img width="1280" alt="msys_gcc" src="https://user-images.githubusercontent.com/5058165/152636695-afc7c807-a8ad-481a-bfe5-61171d3a9f88.png">

<img width="1280" alt="mpi_off" src="https://user-images.githubusercontent.com/5058165/152636692-acffd5a9-b31b-459e-aff9-5ba8c7a7354b.png">
ontent.com/5058165/152636679-bc0484d9-c808-4670-b519-d84c170eeab2.png">
<img width="1280" alt="m
<img width="418" alt="system_va
<img width="932" alt="user_variable" src="https://user-images.githubusercontent.com/5058165/152636711-7dcb6dee-3492-4109-b3a2-3acc8c05c9b8.png">
riable" src="https://user-images.githubusercontent.com/5058165/152636707-7186372e-5fba-4479-8adb-ec6878f0d139.png">

<img width="265" alt="system_path" src="https://user-images.githubusercontent.com/5058165/152636702-2ae3fae6-d9eb-4b0c-a760-7e3d0035eb89.png">

<img width="1261" alt="msys2" src="https://user-images.githubusercontent.com/5058165/152636701-e4d6d5aa-396d-4615-aac7-461f3008dbbb.png">
sys_mpi" src="https://user-images.githubusercontent.com/5058165/152636698-fb2a1132-d13f-49e7-a0d6-a853c60757e3.png">

Fortran compiler is intel.  I am making mpi off using options.cmake file. Without MPI also, there are errors which is stopping the build but at installation stage.

**Comment by himanshu10140** [comment]
<img width="1280" alt="MPI_error" src="https://user-images.githubusercontent.com/5058165/152636804-32357c09-1034-4c46-adbc-25e0c01ec97a.png">
<img width="1280" alt="msys_gcc" src="https://user-images.githubusercontent.com/5058165/152636805-4c3b8bd3-affb-4ce1-9ef4-a10fe1dd238f.png">
<img width="1280" alt="mpi_off" src="https://user-images.githubusercontent.com/5058165/152636807-d67736ba-a99b-4acf-a171-78e7271bddf7.png">
<img width="1280" alt="msys_mpi" src="https://user-images.githubusercontent.com/5058165/152636809-d0f51067-2598-480c-9456-77cbc6d7fad3.png">
<img width="1261" alt="msys2" src="https://user-images.githubusercontent.com/5058165/152636811-0d6997c3-0454-481b-a657-e80016bdbcfb.png">
<img width="265" alt="system_path" src="https://user-images.githubusercontent.com/5058165/152636813-a047699a-8166-4fd1-963d-3d2ca2d54b78.png">
<img width="418" alt="system_variable" src="https://user-images.githubusercontent.com/5058165/152636820-62198fb0-24f8-4d91-94fd-019877a2a0ef.png">
<img width="932" alt="user_variable" src="https://user-images.githubusercontent.com/5058165/152636823-556c156c-2101-4f3c-9b9b-0998c450a2ca.png">

**Comment by scivision** [comment]
This was just at the time we were changing to building libraries one-time via a separate project. This is probably the main problem.

The Visual Studio generator won't work with several of the projects, including Gemini3D itself. I just added a warning message for this. 

The Intel compiler on Windows must use its own Intel MPI, this should be detected automatically. I would use the latest Intel oneAPI 2022.1 or newer as the older beta 2021 versions have general problems.

You don't use any MSYS2 libraries with Intel oneAPI, the gemini3d/external project will build what's missing.

**Comment by scivision** [comment]
[Intel oneAPI](https://www.scivision.dev/intel-oneapi-fortran-install/) provides Intel MPI, LAPACK, and Scalapack on Windows. We do not use MSYS2/GCC libraries with Windows oneAPI as they are ABI incompatible. Use the oneAPI Command Prompt on Windows.

**Comment by scivision** [comment]
So from the oneAPI command prompt Window you would do:

```sh
git clone https://github.com/gemini3d/external
cmake -S external -B external/build -DCMAKE_INSTALL_PREFIX=~/lib_intel
cmake --build external/build
```
that installs Gemini3d external libraries under ~/lib_intel (c:/users/username/lib_intel)

Now install and test gemin3d
```sh
git clone https://github.com/gemini3d/gemini3d

cmake 0S gemini3d -B build/gemini3d -G Ninja

cmake --build gemini3d/build

ctest --test-dir gemini3d/build
```

**Comment by himanshu10140** [comment]
I am facing some issue with Intel compiler
<img width="1280" alt="intel_error1" src="https://user-images.githubusercontent.com/5058165/159124036-9d8646f0-0603-4541-9d98-95239fff5172.png">
.

**Comment by scivision** [comment]
This looks like a compiler environment problem. I would try 

* a fresh build directory (i.e. delete old build info) 
* use the oneAPI command prompt under Start Menu | Intel oneAPI 2022 | oneAPI command prompt for Intel 64 for Visual Studio 2022  (visual studio 2019 is also OK)

**Comment by himanshu10140** [comment]
Finally, I am able to install in windows using only msys. I was able to integrate mat gemini. I am facing some issues with example runs for which I am opening a new issue. Thank you.
